# Generated by Django 4.1.5 on 2023-03-28 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cadastros", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Usuario",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "data_inclusao",
                    models.DateTimeField(auto_now=True, verbose_name="data inclusão"),
                ),
                (
                    "data_alteracao",
                    models.DateTimeField(auto_now=True, verbose_name="data alteração"),
                ),
                (
                    "data_exclusao",
                    models.DateTimeField(auto_now=True, verbose_name="data exclusão"),
                ),
            ],
        ),
        migrations.AddField(
            model_name="categoria",
            name="data_alteracao",
            field=models.DateTimeField(auto_now=True, verbose_name="data alteração"),
        ),
        migrations.AddField(
            model_name="categoria",
            name="data_exclusao",
            field=models.DateTimeField(auto_now=True, verbose_name="data exclusão"),
        ),
        migrations.AddField(
            model_name="categoria",
            name="data_inclusao",
            field=models.DateTimeField(auto_now=True, verbose_name="data inclusão"),
        ),
        migrations.AddField(
            model_name="subcategoria",
            name="data_alteracao",
            field=models.DateTimeField(auto_now=True, verbose_name="data alteração"),
        ),
        migrations.AddField(
            model_name="subcategoria",
            name="data_exclusao",
            field=models.DateTimeField(auto_now=True, verbose_name="data exclusão"),
        ),
        migrations.AddField(
            model_name="subcategoria",
            name="data_inclusao",
            field=models.DateTimeField(auto_now=True, verbose_name="data inclusão"),
        ),
        migrations.AlterField(
            model_name="categoria",
            name="descricao",
            field=models.CharField(max_length=100, verbose_name="descrição"),
        ),
        migrations.AlterField(
            model_name="empresa",
            name="data_alteracao",
            field=models.DateTimeField(auto_now=True, verbose_name="data alteração"),
        ),
        migrations.AlterField(
            model_name="empresa",
            name="data_exclusao",
            field=models.DateTimeField(auto_now=True, verbose_name="data exclusão"),
        ),
        migrations.AlterField(
            model_name="empresa",
            name="data_inclusao",
            field=models.DateTimeField(auto_now=True, verbose_name="data inclusão"),
        ),
        migrations.AlterField(
            model_name="empresa",
            name="email",
            field=models.EmailField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name="empresa",
            name="endereco",
            field=models.CharField(max_length=100, verbose_name="endereço"),
        ),
    ]
