# Generated by Django 4.1.5 on 2023-04-11 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cadastros", "0002_usuario_categoria_data_alteracao_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Promocao",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "data_inclusao",
                    models.DateTimeField(auto_now=True, verbose_name="data inclusão"),
                ),
                (
                    "data_alteracao",
                    models.DateTimeField(auto_now=True, verbose_name="data alteração"),
                ),
                (
                    "data_exclusao",
                    models.DateTimeField(auto_now=True, verbose_name="data exclusão"),
                ),
                ("data_inicio", models.DateTimeField()),
                ("data_fim", models.DateTimeField()),
            ],
        ),
        migrations.DeleteModel(
            name="Usuario",
        ),
    ]
