# Generated by Django 4.1.5 on 2023-04-25 00:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("cadastros", "0003_promocao_delete_usuario"),
    ]

    operations = [
        migrations.CreateModel(
            name="Produto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "data_inclusao",
                    models.DateTimeField(auto_now=True, verbose_name="data inclusão"),
                ),
                (
                    "data_alteracao",
                    models.DateTimeField(auto_now=True, verbose_name="data alteração"),
                ),
                (
                    "data_exclusao",
                    models.DateTimeField(auto_now=True, verbose_name="data exclusão"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Venda",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "data_inclusao",
                    models.DateTimeField(auto_now=True, verbose_name="data inclusão"),
                ),
                (
                    "data_alteracao",
                    models.DateTimeField(auto_now=True, verbose_name="data alteração"),
                ),
                (
                    "data_exclusao",
                    models.DateTimeField(auto_now=True, verbose_name="data exclusão"),
                ),
                ("telefone_cliente", models.CharField(max_length=15)),
                ("data_venda", models.DateTimeField()),
                ("data_pagamento", models.DateTimeField()),
                (
                    "promocao",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="cadastros.promocao",
                    ),
                ),
            ],
        ),
    ]
