# Generated by Django 4.1.5 on 2023-05-09 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cadastros", "0004_produto_venda"),
    ]

    operations = [
        migrations.AlterField(
            model_name="categoria",
            name="data_inclusao",
            field=models.DateTimeField(auto_now_add=True, verbose_name="data inclusão"),
        ),
        migrations.AlterField(
            model_name="empresa",
            name="data_inclusao",
            field=models.DateTimeField(auto_now_add=True, verbose_name="data inclusão"),
        ),
        migrations.AlterField(
            model_name="produto",
            name="data_inclusao",
            field=models.DateTimeField(auto_now_add=True, verbose_name="data inclusão"),
        ),
        migrations.AlterField(
            model_name="promocao",
            name="data_exclusao",
            field=models.DateTimeField(null=True, verbose_name="data exclusão"),
        ),
        migrations.AlterField(
            model_name="promocao",
            name="data_inclusao",
            field=models.DateTimeField(auto_now_add=True, verbose_name="data inclusão"),
        ),
        migrations.AlterField(
            model_name="subcategoria",
            name="data_inclusao",
            field=models.DateTimeField(auto_now_add=True, verbose_name="data inclusão"),
        ),
        migrations.AlterField(
            model_name="venda",
            name="data_inclusao",
            field=models.DateTimeField(auto_now_add=True, verbose_name="data inclusão"),
        ),
    ]
