# Generated by Django 4.1.5 on 2023-05-09 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cadastros", "0005_alter_categoria_data_inclusao_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="promocao",
            name="descricao",
            field=models.CharField(
                default="teste", max_length=200, verbose_name="descrição"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="promocao",
            name="titulo_promocao",
            field=models.CharField(
                default="teste", max_length=50, verbose_name="titulo promoção"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="promocao",
            name="valor",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=11),
            preserve_default=False,
        ),
    ]
