# Generated by Django 4.1.5 on 2023-05-09 01:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("cadastros", "0006_promocao_descricao_promocao_titulo_promocao_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="produto",
            name="categoria",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.PROTECT,
                to="cadastros.categoria",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="produto",
            name="descricao",
            field=models.CharField(
                default="teste", max_length=200, verbose_name="descrição"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="produto",
            name="nome_produto",
            field=models.CharField(default="teste", max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="produto",
            name="preco",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=11),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="produto",
            name="subcategoria",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.PROTECT,
                to="cadastros.subcategoria",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="venda",
            name="endereco_montagem",
            field=models.CharField(
                default="teste", max_length=200, verbose_name="endereço montagem"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="venda",
            name="nome_cliente",
            field=models.CharField(default="teste", max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="venda",
            name="total",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=11),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="categoria",
            name="data_exclusao",
            field=models.DateTimeField(null=True, verbose_name="data exclusão"),
        ),
        migrations.AlterField(
            model_name="empresa",
            name="data_exclusao",
            field=models.DateTimeField(null=True, verbose_name="data exclusão"),
        ),
        migrations.AlterField(
            model_name="subcategoria",
            name="data_exclusao",
            field=models.DateTimeField(null=True, verbose_name="data exclusão"),
        ),
        migrations.AlterField(
            model_name="venda",
            name="data_exclusao",
            field=models.DateTimeField(null=True, verbose_name="data exclusão"),
        ),
    ]
