# Generated by Django 4.1.5 on 2023-06-06 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cadastros", "0009_remove_categoria_atualizado_por_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="empresa",
            name="status",
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
    ]
