# Generated by Django 4.2.2 on 2024-10-11 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0011_alter_categoria_alterado_por_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='venda',
            name='pago',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='venda',
            name='pegue_monte',
            field=models.BooleanField(default=False),
        ),
    ]
